=== Freshdouble/xcode/xcm.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.w3schools.com" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="math" type="xs:string"/>
<xs:element name="unit" type="xs:string"/>
<xs:element name="entry">
  <xs:complexType mixed="true">
    <xs:sequence>
      <xs:element ref="w3s:math" minOccurs="0" xmlns:w3s="http://www.w3schools.com"/>
      <xs:element ref="w3s:unit" minOccurs="0" xmlns:w3s="http://www.w3schools.com"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="required"/>
    <xs:attribute type="xs:int" name="length" use="optional"/>
    <xs:attribute type="xs:string" name="type" use="required"/>
    <xs:attribute type="xs:byte" name="bitlength" use="optional"/>
    <xs:attribute type="xs:string" name="value" use="optional"/>
    <xs:attribute type="xs:string" name="visibility" use="optional"/>
    <xs:attribute type="xs:int" name="maxlength" use="optional"/>
    <xs:attribute type="xs:boolean" name="isvisible" use="optional"/>
    <xs:attribute type="xs:int" name="historylength" use="optional"/>
    <xs:attribute type="xs:boolean" name="hashistory" use="optional"/>
    <xs:attribute type="xs:string" name="historytype" use="optional"/>
    <xs:attribute type="xs:string" name="check" use="optional"/>
    <xs:attribute type="xs:boolean" name="importand" use="optional"/>
    <xs:attribute type="xs:boolean" name="fixed" use="optional"/>
  </xs:complexType>
</xs:element>
<xs:element name="symbol">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="w3s:entry" maxOccurs="unbounded" minOccurs="0" xmlns:w3s="http://www.w3schools.com"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="optional"/>
    <xs:attribute type="xs:string" name="ref" use="optional"/>
  </xs:complexType>
</xs:element>
<xs:element name="message">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="w3s:symbol" xmlns:w3s="http://www.w3schools.com" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="required"/>
    <xs:attribute type="xs:string" name="identifier" use="required"/>
    <xs:attribute type="xs:string" name="identfiierType" use="required"/>
    <xs:attribute type="xs:unsignedInt" name="idoffset" use="optional"/>
    <xs:attribute type="xs:unsignedInt" name="idlength" use="optional"/>
  </xs:complexType>
</xs:element>
  <xs:element name="command">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="w3s:symbol" xmlns:w3s="http://www.w3schools.com"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="name" use="required"/>
      <xs:attribute type="xs:string" name="identifier" use="required"/>
      <xs:attribute type="xs:string" name="identfiierType" use="required"/>
    </xs:complexType>
  </xs:element>
<xs:element name="symbols">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="w3s:symbol" maxOccurs="unbounded" minOccurs="0" xmlns:w3s="http://www.w3schools.com"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>
<xs:element name="messages">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="w3s:message" maxOccurs="unbounded" minOccurs="0" xmlns:w3s="http://www.w3schools.com"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>
  <xs:element name="commands">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="w3s:command" maxOccurs="unbounded" minOccurs="0" xmlns:w3s="http://www.w3schools.com"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
<xs:element name="spacesystem">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="w3s:symbols" maxOccurs="1" xmlns:w3s="http://www.w3schools.com"/>
      <xs:element ref="w3s:messages" maxOccurs="1" xmlns:w3s="http://www.w3schools.com"/>
      <xs:element ref="w3s:commands" maxOccurs="1" xmlns:w3s="http://www.w3schools.com"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>
</xs:schema>

=== Freshdouble/xcode/xcodegen/FMSXCM.xml
<?xml version="1.0" encoding="utf-8" ?>
<spacesystem xmlns="http://www.w3schools.com"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://www.w3.org/2001/XMLSchema xcm.xsd">
  <symbols>
  </symbols>
  <messages>
    <message name="Status" identifier="$RFD50" identfiierType="string">
      <!--Paket to transmit the current device status-->
	  <!--Testcomment-->
      <symbol name="Data1">
		  <!--Bitfield with the current status-->
        <entry name="adc_initialized" type="bool" value="false"/>
        <entry name="dac_initialized" type="bool" value="false"/>
        <entry name="dma_initialized" type="bool" value="false"/>
        <entry name="flash_ssp_initialized" type="bool" value="false"/>
        <entry name="i2c0_initialized" type="bool" value="false"/>
        <entry name="i2c1_initialized" type="bool" value="false"/>
        <entry name="i2c2_initialized" type="bool" value="false"/>
        <entry name="uart0_initialized" type="bool" value="false"/>
        <entry name="uart1_initialized" type="bool" value="false"/>
        <entry name="uart2_initialized" type="bool" value="false"/>
        <entry name="uart3_initialized" type="bool" value="false"/>
        <entry name="rtc_initialized" type="bool" value="false"/>
        <entry name="ssp1_initialized" type="bool" value="false"/>
        <entry name="structs_initialized" type="bool" value="false"/>
        <entry name="systick_initialized" type="bool" value="false"/>
        <entry name="timer1_initialized" type="bool" value="false"/>
        <entry name="watchdog_initialized" type="bool" value="false"/>
        <entry name="eeprom_initialized" type="bool" value="false"/>
        <entry name="ars_initialized" type="bool" value="false"/>
        <entry name="power_management_initialized" type="bool" value="false"/>
        <entry name="flash_initialized" type="bool" value="false"/>
        <entry name="seven_segment_intern_initialized" type="bool" value="false"/>
        <entry name="seven_segment_extern_initialized" type="bool" value="false"/>
        <entry name="startup_success" type="bool" value="false"/>
        <entry name="sensor_pressure_initialized" type="bool" value="false"/>
        <entry name="startup_checked" type="bool" value="false"/>
        <entry name="sensor_imu_initialized" type="bool" value="false"/>
        <entry name="notused1" type="bool" value="false"/>
        <entry name="sensor_hig_initialized" type="bool" value="false"/>
        <entry name="sensor_gyro_initialized" type="bool" value="false"/>
        <entry name="gnss_ready" type="bool" value="false"/>
        <entry name="notused2" type="bool" value="false"/>
      </symbol>
      <symbol name="Ignitervoltages">
        <entry name="igniter_1_voltage" type="uint" bitlength="16"/>
        <entry name="igniter_2_voltage" type="uint" bitlength="16"/>
        <entry name="igniter_3_voltage" type="uint" bitlength="16"/>
        <entry name="igniter_4_voltage" type="uint" bitlength="16"/>
        <entry name="igniter_hpower_voltage" type="uint" bitlength="16"/>
      </symbol>
      <symbol>
        <entry name="orientation" type="uint" bitlength="8"/>
      </symbol>
    </message>
    <message name="BarometricData" identifier="$RFD30" identfiierType="string">
      <symbol>
        <entry name="pressure" type="uint" bitlength="32"/>
      </symbol>
    </message>
  </messages>
  <commands>
    <command name="Testcommand" identifier="$RFCC" identfiierType="string">
      <symbol>
        <entry name="command" type="string" maxlength="50"/>
      </symbol>
    </command>
  </commands>
</spacesystem>

=== Freshdouble/xcode/TestXCM.xml
<?xml version="1.0" encoding="utf-8" ?>
<spacesystem xmlns="http://www.w3schools.com"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://www.w3.org/2001/XMLSchema xcm.xsd">
  <symbols>
  </symbols>
  <messages>
    <message name="Status" identifier="$RFD50" identfiierType="string">
      <!--This paket is a standard status paket.-->
      <symbol name="test">
        <!--Test payload to test the decoder and encoder-->
        <entry name="Testdata" type="uint" bitlength="16" value="32767000">
          <!--Some Testdata with a fixed value-->
        </entry>
        <entry name="TestBool" type="bool" value="true"/>
      </symbol>
    </message>
    <message name="BarometricData" identifier="$RFD50" identfiierType="string">
      <symbol>
        <entry name="timestamp" type="uint" bitlength="32"/>
        <entry name="preassure" type="double"/>
        <entry name="speed" type="double" visibility="virtual">
          <math>preassure_diff/timestamp_diff</math>
        </entry>
        <entry name="teststring" type="string" maxlength="50"/>
      </symbol>
    </message>
  </messages>
  <commands>
    <command name="Testcommand" identifier="$RFCC" identfiierType="string">
      <symbol>
        <entry name="command" type="string" length="10" value="RST"/>
      </symbol>
    </command>
  </commands>
</spacesystem>
